[phases.setup]
commands = [
  # Mostrar información del sistema operativo para depuración
  "cat /etc/os-release",
  
  # Instalar dependencias necesarias
  "apt-get update && apt-get install -y gnupg2 unixodbc unixodbc-dev libgssapi-krb5-2 curl lsb-release apt-transport-https",
  
  # Agregar clave y repositorio de Microsoft
  "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
  "curl https://packages.microsoft.com/config/debian/11/prod.list -o /etc/apt/sources.list.d/mssql-release.list",
  
  # Actualizar repositorios e instalar drivers
  "apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18",
  
  # Instalar extensiones de PHP para SQL Server
  "pecl install pdo_sqlsrv sqlsrv",
  "docker-php-ext-enable pdo_sqlsrv sqlsrv"
]
