[phases.setup]
commands = [
  # Instalar dependencias necesarias
  "apt-get update && apt-get install -y gnupg2 openssl unixodbc unixodbc-dev libgssapi-krb5-2 curl lsb-release apt-transport-https libssl-dev ca-certificates build-essential autoconf php-dev",
  
  # Agregar clave y repositorio de Microsoft
  "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
  "curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list",
  
  # Actualizar repositorios e instalar drivers de SQL Server
  "apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18",
  "apt-get update && apt-get install -y php-common php-cli",
  "pecl channel-update pecl.php.net",
]

[phases.install]
commands = [
  # Crear un directorio para configuraciones adicionales
  "mkdir -p /app/php-config",

  # Agregar las extensiones necesarias
  "echo 'extension=filter.so' > /app/php-config/20-filter.ini",
  "echo 'extension=openssl.so' > /app/php-config/22-pdo_sqlsrv.ini",

  # Descargar el certificado al directorio de configuraciones
  "curl -o /app/php-config/ca-certificates.crt https://curl.se/ca/cacert.pem",

  # Configurar OpenSSL para usar el certificado descargado
  "echo 'openssl.cafile=/app/php-config/ca-certificates.crt' > /app/php-config/30-ssl-cert.ini",

  # Configurar PHP para escanear este directorio
  "echo 'export PHP_INI_SCAN_DIR=/app/php-config' >> /etc/environment",
  "echo 'openssl.cafile=/app/php-config/ca-certificates.crt' >> /nix/store/b2firg72rd7mjry2vlw7shhzqxhdzic9-php-with-extensions-8.2.22/lib/php.ini",
  "phpenmod openssl",

  # Instalar las últimas versiones de sqlsrv y pdo_sqlsrv desde PECL
  "pecl install sqlsrv",
  "pecl install pdo_sqlsrv",

  "echo 'extension=sqlsrv.so' > /app/php-config/20-sqlsrv.ini",
  "echo 'extension=pdo_sqlsrv.so' > /app/php-config/21-pdo_sqlsrv.ini",

  # Instalar dependencias de Laravel
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "composer install --ignore-platform-reqs",
  "php artisan optimize",
  "npm ci",
  "php --ini",
  "php --ri sqlsrv",
  "php --ri pdo_sqlsrv",
  "php -i | grep sqlsrv",
  "php -i | grep openssl",
  "php -d PHP_INI_SCAN_DIR=/app/php-config -i | grep openssl"
]
