[phases.setup]
commands = [
  "apt-get update && apt-get install -y gnupg2 unixodbc unixodbc-dev libgssapi-krb5-2 curl lsb-release apt-transport-https libssl-dev ca-certificates build-essential autoconf",
  "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
  "curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list",
  "apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18"
]

[phases.install]
commands = [
  # Descargar el paquete pdo_sqlsrv
  "curl -O https://pecl.php.net/get/pdo_sqlsrv-5.12.0.tgz",
  "tar -xzf pdo_sqlsrv-5.12.0.tgz",
  "cd pdo_sqlsrv-5.12.0 && phpize && ./configure && make && make install",
  # Habilitar la extensión
  "docker-php-ext-enable pdo_sqlsrv",

  # Descargar el paquete sqlsrv
  "curl -O https://pecl.php.net/get/sqlsrv-5.12.0.tgz",
  "tar -xzf sqlsrv-5.12.0.tgz",
  "cd sqlsrv-5.12.0 && phpize && ./configure && make && make install",
  # Habilitar la extensión
  "docker-php-ext-enable sqlsrv",
]

